---
kind: Pod
apiVersion: v1
metadata:
  name: haproxy
  namespace: openshift-kni-infra
  creationTimestamp:
  deletionGracePeriodSeconds: 65
  labels:
    app: kni-infra-api-lb
spec:
  volumes:
  - name: resource-dir
    hostPath:
      path: "/etc/kubernetes/static-pod-resources/haproxy"
  - name: kubeconfig
    hostPath:
      path: "/etc/kubernetes/kubeconfig"
  - name: run-dir
    empty-dir: {}
  - name: conf-dir
    empty-dir: {}
  - name: chroot-host
    hostPath:
      path: "/"
  initContainers:
  - name: clusterrc-generation
    image: quay.io/openshift-metal3/kubeconfig-extractor:latest
    command:
    - "/usr/bin/kubeconfig-extractor"
    args:
    - "/etc/kubernetes/kubeconfig"
    - "/etc/kubernetes/static-pod-resources/clusterrc"
    resources: {}
    volumeMounts:
    - name: resource-dir
      mountPath: "/etc/kubernetes/static-pod-resources"
    - name: kubeconfig
      mountPath: "/etc/kubernetes/kubeconfig"
  - name: render-haproxy-cfg
    image: quay.io/openshift/origin-node:latest
    env:
    - name: api_port
      value: "6443"
    - name: stat_port
      value: "50000"
    command:
    - "/bin/bash"
    - "-c"
    - |
      #/bin/bash
      set -ex

      source /etc/kubernetes/static-pod-resources/clusterrc
      source /etc/kubernetes/static-pod-resources/utils.sh
      generate_cfg \
          /etc/kubernetes/static-pod-resources/haproxy.cfg.template \
          /etc/haproxy/haproxy.cfg \
          "$DOMAIN" \
          "$api_port" \
          "$stat_port"
    resources: {}
    volumeMounts:
    - name: resource-dir
      mountPath: "/etc/kubernetes/static-pod-resources"
    - name: conf-dir
      mountPath: "/etc/haproxy"
    imagePullPolicy: IfNotPresent
  containers:
  - name: haproxy
    image: docker.io/library/haproxy:latest
    args:
    - "-W"
    - "-db"
    - "-S"
    - "/var/run/haproxy/haproxy-master.sock,level,admin"
    - "-f"
    - "/etc/haproxy/haproxy.cfg"
    volumeMounts:
    - name: conf-dir
      mountPath: "/etc/haproxy"
    - name: run-dir
      mountPath: "/var/run/haproxy"
    terminationMessagePolicy: FallbackToLogsOnError
    imagePullPolicy: IfNotPresent
  - name: haproxy-monitor
    securityContext:
      privileged: true
    image: quay.io/openshift/origin-node:latest
    env:
    - name: cfg_path
      value: "/etc/haproxy/haproxy.cfg"
    - name: api_port
      value: "6443"
    - name: lb_port
      value: "7443"
    - name: stat_port
      value: "50000"
    command:
    - "/bin/bash"
    - "-c"
    - |
      #/bin/bash
      set -ex

      source /etc/kubernetes/static-pod-resources/clusterrc
      source /etc/kubernetes/static-pod-resources/utils.sh
      API_VIP="$(dig +noall +answer "api.${DOMAIN}" | awk '{print $NF}')"

      trap clean_prerouting_rules SIGINT SIGTERM
      while true; do
          sleep 15
          if has_master_api_lb_topology_changed "$DOMAIN" "$cfg_path"; then
              (>&2 echo "Master topology changed. Reconfiguring and hot restarting HAProxy")
              generate_cfg \
                  /etc/kubernetes/static-pod-resources/haproxy.cfg.template \
                  "$cfg_path" \
                  "$DOMAIN" \
                  "$api_port" \
                  "$stat_port"
              echo "reload" | socat /var/run/haproxy/haproxy-master.sock -
          fi
          if curl -o /dev/null -kLs "https://0:${lb_port}/healthz"; then
              (>&2 echo "API is accessible via LB")
              ensure_prerouting_rules "$API_VIP" "$api_port" "$lb_port"
          fi
      done
    volumeMounts:
    - name: conf-dir
      mountPath: "/etc/haproxy"
    - name: run-dir
      mountPath: "/var/run/haproxy"
    - name: resource-dir
      mountPath: "/etc/kubernetes/static-pod-resources"
    - name: chroot-host
      mountPath: "/host"
    terminationMessagePolicy: FallbackToLogsOnError
    imagePullPolicy: IfNotPresent
  hostNetwork: true
  tolerations:
  - operator: Exists
  priorityClassName: system-node-critical
status: {}
